# CashewMath
# Keegan Kochis

notifications:
  email: false

language: c++
sudo: false

compiler:
  - clang
  - gcc
  - msvc

os:
  - linux

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ctest
